_HallOfFameOakText::
	text "OAK: Er-hem!"
	para "Tebrikler,"
	line "Congratulations,"
	para "<PLAYER>!"
	line "<PLAYER>!"

	para "Bu kat"
	line "This floor is the"
	para "#MON SALONU"
	line "#MON HALL OF"
	para "ŞÖHRET!"
	line "FAME!"

	para "#MON LİGİ"
	line "#MON LEAGUE"
	para "şampiyonlar"
	line "champions are"
	para "onların adına on"
	line "urlandırıldı"
	para "honored for their"
	para "burada istismar "
	line "ediyor"
	para "exploits here!"

	para "Onların #MON'lar"
	line ""
	para "Their #MON are"
	para "ayrıca kaydedild"
	line ""
	para "also recorded in"
	para "şöhret salonu!"
	line "the HALL OF FAME!"

	para "<PLAYER>! Var"
	line "<PLAYER>! You have"
	para "çok çabaladım"
	line "endeavored hard"
	para "yeni olmak"
	line "to become the new"
	para "LİG şampiyonu!"
	line "LEAGUE champion!"

	para "Tebrikler,"
	line "Congratulations,"
	para "<PLAYER>, sen ve"
	line "<PLAYER>, you and"
	para "#MON'unuz"
	line "your #MON are"
	para "FAMER'LAR SALONU"
	line ""
	para "HALL OF FAMERs!"
	done
