_IndigoPlateauLobbyGymGuideText::
	text "Hey! Şampiyon"
	para "yapımı!"
	line "making!"

	para "#MON LEAGUE'de,"
	line "At #MON LEAGUE,"
	para "yüzleşmek zorund"
	line "ası"
	para "you have to face"
	para "ELİT DÖRTLÜ"
	line "the ELITE FOUR in"
	para "halefiyet."
	line "succession."

	para "Eğer kaybedersen"
	line ", se"
	para "If you lose, you"
	para "her şeye başlama"
	line "k zorundayı"
	para "have to start all"
	para "tekrar tekrar! B"
	line ""
	para "over again! This"
	para "bu mu! Göreyim s"
	line "eni"
	para "is it! Go for it!"
	done

_IndigoPlateauLobbyCooltrainerFText::
	text "Bundan sonra sen"
	para "ELİT'le yüzleş"
	line "face the ELITE"
	para "DÖRT tane birer "
	line "birer"
	para "FOUR one by one!"

	para "Eğer kazanırsan,"
	line " bi"
	para "If you win, a"
	para "kapı ona açılır"
	line "door opens to the"
	para "sonraki antrenör"
	line ""
	para "next trainer!"
	para "İyi şanlar!"
	line "Good luck!"
	done
