_LancesRoomLanceBeforeBattleText::
	text "Ah! şunu duydum"
	para "sen, <PLAYER>!"
	line "you, <PLAYER>!"

	para "ELITE'e liderlik"
	line " ediyoru"
	para "I lead the ELITE"
	para "DÖRT! Yapabilirs"
	line "ini"
	para "FOUR! You can"
	para "bana LANCE de"
	line "call me LANCE the"
	para "ejderha eğitmeni"
	line ""
	para "dragon trainer!"

	para "Bunu biliyorsun"
	line "You know that"
	para "ejderhalar"
	line "dragons are"
	para "efsanevi #MON!"
	line "mythical #MON!"

	para "Bunu yapmak zor"
	line "They're hard to"
	para "yakala ve kaldır"
	line ""
	para "catch and raise,"
	para "ama onların güçl"
	line "er"
	para "but their powers"
	para "üstünler!"
	line "are superior!"

	para "Onlar neredeyse"
	line "They're virtually"
	para "yıkılmaz!"
	line "indestructible!"

	para "Peki sen misin"
	line "Well, are you"
	para "kaybetmeye hazır"
	line " mısın"
	para "ready to lose?"

	para "LİGİNİZ"
	line "Your LEAGUE"
	para "meydan okuma son"
	line "a eriyo"
	para "challenge ends"
	para "benimle, <PLAYER>!"
	line "with me, <PLAYER>!"
	done

_LancesRoomLanceEndBattleText::
	text "Bu kadar!"

	para "itiraf etmekten "
	line "nefret ediyoru"
	para "I hate to admit"
	para "o, ama sen bir"
	line "it, but you are a"
	para "#MON usta!"
	line "#MON master!"
	prompt

_LancesRoomLanceAfterBattleText::
	text "hala yapamıyorum"
	para "inan bana"
	line "believe my"
	para "ejderhalar kaybe"
	line "tt"
	para "dragons lost to"
	para "sen, <PLAYER>!"
	line "you, <PLAYER>!"

	para "sen artık"
	line "You are now the"
	para "#MON LİGİ"
	line "#MON LEAGUE"
	para "şampiyon!"
	line "champion!"

	para "...Ya da sen"
	line "...Or, you would"
	para "oldu ama"
	line "have been, but"
	para "bir tane daha va"
	line ""
	para "you have one more"
	para "İleriye meydan o"
	line "kuyun"
	para "challenge ahead."

	para "yüzleşmek zorund"
	line "ası"
	para "You have to face"
	para "başka bir antren"
	line "ör"
	para "another trainer!"
	para "Onun adı..."
	line "His name is..."

	para "<RIVAL>!"
	line "<RIVAL>!"
	para "ELİT'i yendi"
	line "He beat the ELITE"
	para "DÖRT önünüzde!"
	line "FOUR before you!"

	para "O gerçek"
	line "He is the real"
	para "#MON LİGİ"
	line "#MON LEAGUE"
	cont "şampiyon!@"
	text_end
